import copy
import random
from datetime import date
from typing import Any, Dict, List

from django.utils import timezone


_DAILY_RECIPE_POOL: Dict[str, List[Dict[str, Any]]] = {
    "easy": [
        {
            "id": "daily_easy_tomato_egg_scramble",
            "title": "Tomato Egg Scramble Toast",
            "description": "Soft scrambled eggs with sweet tomatoes and herbs on warm toast.",
            "cook_time_minutes": 15,
            "difficulty": "Easy",
            "servings": 2,
            "pantry_match_percent": 92,
            "ingredients": ["eggs", "tomatoes", "olive oil", "salt", "black pepper", "bread"],
            "used_pantry_ingredients": ["eggs", "tomatoes", "olive oil", "salt", "black pepper"],
            "missing_ingredients": ["bread"],
            "why_suggested": "Fast, high-protein breakfast using common pantry staples.",
            "steps": [
                "Dice tomatoes and season lightly with salt so they release juices.",
                "Warm olive oil in a skillet, add tomatoes, and cook for 3 minutes until jammy.",
                "Beat eggs with pepper, pour in, and stir gently over low heat for 2 to 3 minutes.",
                "Serve on toasted bread and finish with extra olive oil.",
            ],
            "macros": {"calories": "360 kcal", "protein": "19 g", "carbs": "25 g", "fat": "18 g"},
            "equipment": ["Non-stick skillet", "Spatula", "Mixing bowl"],
            "chef_tip": "Turn off the heat when eggs look slightly underdone; carryover heat makes them creamy.",
            "image_url": "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80",
        },
        {
            "id": "daily_easy_garlic_tomato_linguine",
            "title": "Garlic Tomato Linguine",
            "description": "Quick pantry pasta with garlic, olive oil, and crushed tomato.",
            "cook_time_minutes": 18,
            "difficulty": "Easy",
            "servings": 2,
            "pantry_match_percent": 88,
            "ingredients": ["linguine", "garlic", "canned tomatoes", "olive oil", "salt", "basil"],
            "used_pantry_ingredients": ["garlic", "canned tomatoes", "olive oil", "salt"],
            "missing_ingredients": ["linguine", "basil"],
            "why_suggested": "Low-effort comfort food made from shelf staples.",
            "steps": [
                "Boil salted water and cook linguine until al dente.",
                "Saute sliced garlic in olive oil for 1 minute until fragrant.",
                "Add canned tomatoes and simmer 6 minutes to reduce slightly.",
                "Toss pasta with sauce and finish with torn basil before serving.",
            ],
            "macros": {"calories": "510 kcal", "protein": "12 g", "carbs": "78 g", "fat": "15 g"},
            "equipment": ["Pot", "Saute pan", "Tongs"],
            "chef_tip": "Reserve half a cup of pasta water and add gradually for a glossy sauce.",
            "image_url": "https://images.unsplash.com/photo-1622973536968-3ead9e780960?auto=format&fit=crop&w=1200&q=80",
        },
        {
            "id": "daily_easy_chicken_rice_skillet",
            "title": "One-Pan Chicken Rice Skillet",
            "description": "Tender chicken and tomato rice cooked in one pan for easy cleanup.",
            "cook_time_minutes": 25,
            "difficulty": "Easy",
            "servings": 2,
            "pantry_match_percent": 83,
            "ingredients": ["chicken breast", "rice", "onion", "canned tomatoes", "stock", "olive oil"],
            "used_pantry_ingredients": ["chicken breast", "rice", "onion", "canned tomatoes", "stock", "olive oil"],
            "missing_ingredients": [],
            "why_suggested": "Balanced dinner with minimal prep and pantry-first ingredients.",
            "steps": [
                "Cut chicken into bite-size pieces and season with salt and pepper.",
                "Brown chicken in olive oil, then remove and saute onion until translucent.",
                "Add rice, canned tomatoes, and stock; bring to a simmer.",
                "Return chicken, cover, and cook 15 minutes until rice is tender.",
            ],
            "macros": {"calories": "540 kcal", "protein": "35 g", "carbs": "52 g", "fat": "18 g"},
            "equipment": ["Deep skillet with lid", "Wooden spoon", "Knife"],
            "chef_tip": "Let the skillet rest off heat for 5 minutes so steam fully finishes the rice.",
            "image_url": "https://images.unsplash.com/photo-1701579231305-d84d8af9a3fd?auto=format&fit=crop&w=1200&q=80",
        },
        {
            "id": "daily_easy_quick_tomato_soup",
            "title": "Quick Creamy Tomato Soup",
            "description": "Silky tomato soup with garlic and a touch of cream.",
            "cook_time_minutes": 20,
            "difficulty": "Easy",
            "servings": 2,
            "pantry_match_percent": 86,
            "ingredients": ["canned tomatoes", "garlic", "onion", "stock", "cream", "olive oil"],
            "used_pantry_ingredients": ["canned tomatoes", "garlic", "onion", "stock", "olive oil"],
            "missing_ingredients": ["cream"],
            "why_suggested": "Warm and simple meal when you want something fast and comforting.",
            "steps": [
                "Saute chopped onion and garlic in olive oil for 3 minutes.",
                "Add canned tomatoes and stock, then simmer 10 minutes.",
                "Blend until smooth and return to low heat.",
                "Stir in cream, adjust seasoning, and serve hot.",
            ],
            "macros": {"calories": "290 kcal", "protein": "6 g", "carbs": "22 g", "fat": "19 g"},
            "equipment": ["Saucepot", "Blender", "Ladle"],
            "chef_tip": "Blend in batches and vent the lid slightly to avoid pressure buildup from steam.",
            "image_url": "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80",
        },
    ],
    "medium": [
        {
            "id": "daily_medium_lemon_salmon",
            "title": "Lemon Garlic Salmon",
            "description": "Pan-seared salmon finished with lemon-garlic butter sauce.",
            "cook_time_minutes": 28,
            "difficulty": "Medium",
            "servings": 2,
            "pantry_match_percent": 79,
            "ingredients": ["salmon fillets", "garlic", "butter", "lemon", "olive oil", "parsley"],
            "used_pantry_ingredients": ["garlic", "butter", "lemon", "olive oil"],
            "missing_ingredients": ["salmon fillets", "parsley"],
            "why_suggested": "Restaurant-style protein dish with familiar pantry flavors.",
            "steps": [
                "Pat salmon dry and season both sides with salt and pepper.",
                "Sear skin-side down in hot olive oil for 4 to 5 minutes until crisp.",
                "Flip, add butter and garlic, and baste fish for 2 to 3 minutes.",
                "Finish with lemon juice and chopped parsley before plating.",
            ],
            "macros": {"calories": "470 kcal", "protein": "34 g", "carbs": "4 g", "fat": "34 g"},
            "equipment": ["Cast-iron skillet", "Spoon for basting", "Fish spatula"],
            "chef_tip": "Press the salmon gently during the first minute so the skin crisps evenly.",
            "image_url": "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=80",
        },
        {
            "id": "daily_medium_arrabbiata",
            "title": "Spicy Arrabbiata Linguine",
            "description": "Bright tomato sauce with garlic and chili layered onto linguine.",
            "cook_time_minutes": 30,
            "difficulty": "Medium",
            "servings": 2,
            "pantry_match_percent": 84,
            "ingredients": ["linguine", "garlic", "canned tomatoes", "chili flakes", "olive oil", "parmesan"],
            "used_pantry_ingredients": ["garlic", "canned tomatoes", "olive oil"],
            "missing_ingredients": ["linguine", "chili flakes", "parmesan"],
            "why_suggested": "A flavorful pasta upgrade when you want more heat and depth.",
            "steps": [
                "Cook linguine in salted water until just al dente.",
                "Bloom chili flakes and garlic in olive oil over medium heat.",
                "Add tomatoes and reduce 10 to 12 minutes for concentrated flavor.",
                "Toss pasta into sauce with parmesan and a splash of pasta water.",
            ],
            "macros": {"calories": "620 kcal", "protein": "18 g", "carbs": "86 g", "fat": "22 g"},
            "equipment": ["Pot", "Wide saute pan", "Microplane"],
            "chef_tip": "Bloom chili gently; scorched chili flakes turn bitter and overpower the sauce.",
            "image_url": "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1200&q=80",
        },
        {
            "id": "daily_medium_tomato_braised_chicken",
            "title": "Tomato-Braised Chicken",
            "description": "Chicken simmered in a rich tomato and herb braising liquid.",
            "cook_time_minutes": 38,
            "difficulty": "Medium",
            "servings": 2,
            "pantry_match_percent": 81,
            "ingredients": ["chicken thighs", "onion", "garlic", "canned tomatoes", "olive oil", "oregano"],
            "used_pantry_ingredients": ["onion", "garlic", "canned tomatoes", "olive oil", "oregano"],
            "missing_ingredients": ["chicken thighs"],
            "why_suggested": "A deeper, slow-simmer flavor profile with pantry-friendly ingredients.",
            "steps": [
                "Sear seasoned chicken thighs until browned on both sides.",
                "Saute onion and garlic in the same pan to build flavor.",
                "Add canned tomatoes and oregano, then return chicken to pan.",
                "Cover and simmer 20 minutes until chicken is tender and cooked through.",
            ],
            "macros": {"calories": "560 kcal", "protein": "38 g", "carbs": "16 g", "fat": "37 g"},
            "equipment": ["Dutch oven", "Tongs", "Wooden spoon"],
            "chef_tip": "Deglaze browned bits with a splash of water before adding tomatoes for extra savory depth.",
            "image_url": "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=1200&q=80",
        },
        {
            "id": "daily_medium_pesto_rosso_pasta",
            "title": "Pesto Rosso Pasta",
            "description": "Sun-dried tomato pesto pasta with toasted garlic and parmesan.",
            "cook_time_minutes": 26,
            "difficulty": "Medium",
            "servings": 2,
            "pantry_match_percent": 75,
            "ingredients": ["pasta", "sun-dried tomatoes", "garlic", "olive oil", "parmesan", "basil"],
            "used_pantry_ingredients": ["garlic", "olive oil"],
            "missing_ingredients": ["pasta", "sun-dried tomatoes", "parmesan", "basil"],
            "why_suggested": "Great flavor payoff with moderate technique and minimal time.",
            "steps": [
                "Cook pasta until al dente and reserve pasta water.",
                "Blend sun-dried tomatoes, garlic, olive oil, and parmesan into a pesto.",
                "Warm pesto in a pan briefly and adjust texture with pasta water.",
                "Toss pasta through sauce and finish with fresh basil.",
            ],
            "macros": {"calories": "640 kcal", "protein": "17 g", "carbs": "84 g", "fat": "27 g"},
            "equipment": ["Food processor", "Pot", "Saute pan"],
            "chef_tip": "Toast the garlic lightly before blending to remove harsh raw notes.",
            "image_url": "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=80",
        },
    ],
    "hard": [
        {
            "id": "daily_hard_confit_tomato_linguine",
            "title": "Confit Tomato Linguine",
            "description": "Slow-roasted tomato confit folded into glossy linguine.",
            "cook_time_minutes": 55,
            "difficulty": "Hard",
            "servings": 2,
            "pantry_match_percent": 74,
            "ingredients": ["cherry tomatoes", "garlic", "olive oil", "linguine", "basil", "parmesan"],
            "used_pantry_ingredients": ["garlic", "olive oil", "basil"],
            "missing_ingredients": ["cherry tomatoes", "linguine", "parmesan"],
            "why_suggested": "A technique-driven pasta that creates deep flavor from simple ingredients.",
            "steps": [
                "Roast tomatoes and garlic in olive oil at low heat for 40 minutes until concentrated.",
                "Cook linguine in heavily salted water until al dente.",
                "Crush roasted tomatoes into the confit oil to form a silky sauce base.",
                "Emulsify pasta with sauce and parmesan, then finish with basil oil.",
            ],
            "macros": {"calories": "680 kcal", "protein": "20 g", "carbs": "92 g", "fat": "26 g"},
            "equipment": ["Oven tray", "Saucepan", "Tongs"],
            "chef_tip": "Keep confit temperature low so garlic sweetens instead of browning.",
            "image_url": "https://images.unsplash.com/photo-1622973536968-3ead9e780960?auto=format&fit=crop&w=1200&q=80",
        },
        {
            "id": "daily_hard_braised_chicken_herbs",
            "title": "Braised Chicken with Herbs",
            "description": "Classic braise with layered aromatics and reduced tomato sauce.",
            "cook_time_minutes": 65,
            "difficulty": "Hard",
            "servings": 2,
            "pantry_match_percent": 77,
            "ingredients": ["chicken thighs", "onion", "garlic", "canned tomatoes", "stock", "thyme"],
            "used_pantry_ingredients": ["onion", "garlic", "canned tomatoes", "stock"],
            "missing_ingredients": ["chicken thighs", "thyme"],
            "why_suggested": "A higher-skill dish focused on layering flavor and texture.",
            "steps": [
                "Sear chicken in batches to build fond, then reserve.",
                "Sweat onion and garlic, then deglaze the pot to lift browned bits.",
                "Add tomatoes, stock, and thyme; return chicken and braise covered for 40 minutes.",
                "Reduce uncovered for 8 minutes for a glossy finish and concentrated flavor.",
            ],
            "macros": {"calories": "610 kcal", "protein": "40 g", "carbs": "19 g", "fat": "41 g"},
            "equipment": ["Dutch oven", "Fine strainer", "Tongs"],
            "chef_tip": "Brown proteins in small batches to avoid steaming and maximize fond development.",
            "image_url": "https://images.unsplash.com/photo-1518492104633-130d0cc84637?auto=format&fit=crop&w=1200&q=80",
        },
        {
            "id": "daily_hard_spicy_tomato_ragu",
            "title": "Slow-Spiced Tomato Ragu",
            "description": "Long-simmered tomato ragu with chili and aromatic depth.",
            "cook_time_minutes": 70,
            "difficulty": "Hard",
            "servings": 2,
            "pantry_match_percent": 72,
            "ingredients": ["canned tomatoes", "onion", "garlic", "olive oil", "chili", "red wine", "linguine"],
            "used_pantry_ingredients": ["canned tomatoes", "onion", "garlic", "olive oil"],
            "missing_ingredients": ["chili", "red wine", "linguine"],
            "why_suggested": "For days when you want rich, developed flavor through slower cooking.",
            "steps": [
                "Caramelize onion slowly in olive oil for 12 minutes.",
                "Add garlic and chili, then deglaze with red wine and reduce by half.",
                "Stir in canned tomatoes and simmer gently for 45 minutes.",
                "Toss with cooked linguine and finish with fresh olive oil.",
            ],
            "macros": {"calories": "700 kcal", "protein": "19 g", "carbs": "103 g", "fat": "23 g"},
            "equipment": ["Heavy pot", "Wooden spoon", "Pasta pot"],
            "chef_tip": "Maintain a gentle burble, not a rapid boil, to keep the ragu smooth and sweet.",
            "image_url": "https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=1200&q=80",
        },
        {
            "id": "daily_hard_herb_crusted_salmon",
            "title": "Herb-Crusted Salmon with Lemon Butter",
            "description": "Crisp herb crusted salmon finished with a silky lemon butter glaze.",
            "cook_time_minutes": 46,
            "difficulty": "Hard",
            "servings": 2,
            "pantry_match_percent": 76,
            "ingredients": ["salmon fillets", "parsley", "dill", "garlic", "butter", "lemon", "olive oil"],
            "used_pantry_ingredients": ["garlic", "butter", "lemon", "olive oil"],
            "missing_ingredients": ["salmon fillets", "parsley", "dill"],
            "why_suggested": "A more advanced fish technique with bright, balanced flavors.",
            "steps": [
                "Pat salmon dry and press a chopped herb-garlic crust onto the flesh side.",
                "Sear salmon crust-side down in olive oil until golden, then flip briefly.",
                "Add butter, baste with foaming fat, and cook to medium doneness.",
                "Deglaze pan with lemon juice, swirl into butter, and spoon over salmon.",
            ],
            "macros": {"calories": "590 kcal", "protein": "39 g", "carbs": "6 g", "fat": "44 g"},
            "equipment": ["Cast-iron skillet", "Fish spatula", "Small saucepan"],
            "chef_tip": "Press the herb crust gently for the first 30 seconds so it adheres and browns evenly.",
            "image_url": "https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=1200&q=80",
        },
    ],
}


def get_daily_suggested_recipes(target_date: date | None = None) -> List[Dict[str, Any]]:
    """Return 6 daily recipe suggestions: 2 easy, 2 medium, 2 hard."""
    today = target_date or timezone.localdate()
    selected: List[Dict[str, Any]] = []

    for difficulty in ("easy", "medium", "hard"):
        pool = _DAILY_RECIPE_POOL.get(difficulty, [])
        if not pool:
            continue

        rng = random.Random(f"souschef-daily::{today.isoformat()}::{difficulty}")
        picks_count = min(2, len(pool))
        selected.extend(copy.deepcopy(rng.sample(pool, picks_count)))

    if len(selected) > 1:
        rng = random.Random(f"souschef-daily::{today.isoformat()}::order")
        rng.shuffle(selected)

    return selected
