from django.db import models
from django.conf import settings

class FavoriteRecipe(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='favorite_recipes')
    recipe_id = models.CharField(max_length=100)
    title = models.CharField(max_length=255)
    image_url = models.URLField(max_length=1000, blank=True, null=True)
    recipe_data = models.JSONField(help_text="Stores the complete JSON payload generated by Gemini.")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'recipe_id')
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.user.username} - {self.title}"
