"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os

try:
    from dotenv import load_dotenv  # type: ignore
except ModuleNotFoundError:  # pragma: no cover
    def load_dotenv(*args, **kwargs):
        return False

load_dotenv()
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Railway/production must set SECRET_KEY in the environment (empty breaks sessions/tests locally).
SECRET_KEY = os.getenv("SECRET_KEY") or "django-insecure-local-only-set-secret-key-in-env"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'


def _env_list(name: str, default: str = "") -> list[str]:
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


def _oauth_env_value(base_name: str) -> str:
    """
    Keep local and production OAuth credentials isolated.
    Priority:
      1) *_LOCAL when DEBUG=True
      2) *_PROD when DEBUG=False
      3) legacy base variable for backward compatibility
    """
    env_specific_name = f"{base_name}_LOCAL" if DEBUG else f"{base_name}_PROD"
    return os.getenv(env_specific_name, "").strip() or os.getenv(base_name, "").strip()


ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS", "localhost,127.0.0.1,.railway.app")
CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS", "")

# Behind Railway / Heroku / Render, the edge terminates TLS; without this, Django
# thinks the request is HTTP and builds http:// OAuth redirect_uri values — Facebook
# Login then shows "isn't using a secure connection".
_trust_proxy_tls = os.getenv("TRUST_PROXY_TLS", "").strip().lower() in (
    "1",
    "true",
    "yes",
)
if _trust_proxy_tls or os.getenv("RAILWAY_ENVIRONMENT"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True


# Application definition

import importlib.util

def _has_module(module_name: str) -> bool:
    try:
        return importlib.util.find_spec(module_name) is not None
    except ModuleNotFoundError:
        return False

_DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
]

_OPTIONAL_THIRD_PARTY_APPS = [
    "crispy_forms",
    "crispy_bootstrap5",
]

_OPTIONAL_ALLAUTH_APPS = [
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
]

_LOCAL_APPS = [
    "users",
    "pantry",
    "recipes",
    "ai_assistant",
    "pages",
    "subscriptions"
]

INSTALLED_APPS = (
    _DJANGO_APPS
    + [app for app in _OPTIONAL_THIRD_PARTY_APPS if _has_module(app)]
    + [app for app in _OPTIONAL_ALLAUTH_APPS if _has_module(app)]
    + _LOCAL_APPS
)

LOGIN_URL = "/users/login/"

ALLAUTH_ENABLED = _has_module("allauth")

if ALLAUTH_ENABLED:
    SITE_ID = int(os.getenv("SITE_ID", "1"))

    AUTHENTICATION_BACKENDS = (
        "django.contrib.auth.backends.ModelBackend",
        "allauth.account.auth_backends.AuthenticationBackend",
    )

    LOGIN_REDIRECT_URL = "/"
    LOGOUT_REDIRECT_URL = "/"

    # Force https in OAuth callback URLs when not debugging (safety net if proxy
    # headers are missing). Override locally with ACCOUNT_DEFAULT_HTTP_PROTOCOL=http.
    _acct_proto = os.getenv("ACCOUNT_DEFAULT_HTTP_PROTOCOL", "").strip().lower()
    if _acct_proto in ("http", "https"):
        ACCOUNT_DEFAULT_HTTP_PROTOCOL = _acct_proto
    elif not DEBUG:
        ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

    ACCOUNT_LOGIN_METHODS = {"username", "email"}
    ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
    ACCOUNT_EMAIL_VERIFICATION = os.getenv("ACCOUNT_EMAIL_VERIFICATION", "none")

    # Social login (Google / Facebook). Prefer env-based credentials; you can
    # alternatively add a Social application in Django admin.
    _google_client_id = _oauth_env_value("GOOGLE_OAUTH_CLIENT_ID")
    _google_client_secret = _oauth_env_value("GOOGLE_OAUTH_CLIENT_SECRET")
    _facebook_client_id = _oauth_env_value("FACEBOOK_OAUTH_CLIENT_ID")
    _facebook_client_secret = _oauth_env_value("FACEBOOK_OAUTH_CLIENT_SECRET")

    SOCIALACCOUNT_PROVIDERS = {
        "google": {
            "SCOPE": ["profile", "email"],
            "AUTH_PARAMS": {"access_type": "online"},
        },
        "facebook": {
            "METHOD": "oauth2",
            "SCOPE": ["email", "public_profile"],
            "FIELDS": [
                "id",
                "first_name",
                "last_name",
                "middle_name",
                "name",
                "name_format",
                "picture",
                "short_name",
                "email",
            ],
        },
    }
    if _google_client_id and _google_client_secret:
        SOCIALACCOUNT_PROVIDERS["google"]["APP"] = {
            "client_id": _google_client_id,
            "secret": _google_client_secret,
            "key": "",
        }
    if _facebook_client_id and _facebook_client_secret:
        SOCIALACCOUNT_PROVIDERS["facebook"]["APP"] = {
            "client_id": _facebook_client_id,
            "secret": _facebook_client_secret,
        }

    # Prefer explicit resolution when both env and DB Social applications exist (see users.adapters).
    SOCIALACCOUNT_ADAPTER = "users.adapters.SocialAccountAdapter"
    # Merge anonymous recipe quota after login (OAuth and allauth account flows).
    ACCOUNT_ADAPTER = "users.account_adapter.AccountAdapter"
    # Skip allauth's intermediate "Sign In Via … / Continue" page; start OAuth immediately (uses site's base styling on your pages only).
    SOCIALACCOUNT_LOGIN_ON_GET = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if ALLAUTH_ENABLED:
    MIDDLEWARE += [
        "allauth.account.middleware.AccountMiddleware",
    ]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

try:
    import dj_database_url  # type: ignore
except ModuleNotFoundError:  # pragma: no cover
    dj_database_url = None

if dj_database_url is None:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    _database_url = os.getenv("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
    _conn_max_age = int(os.getenv("DB_CONN_MAX_AGE", "600"))
    DATABASES = {
        "default": dj_database_url.config(
            default=_database_url,
            conn_max_age=_conn_max_age,
        )
    }
    _db_engine = DATABASES["default"].get("ENGINE", "")
    _is_postgres = "postgresql" in _db_engine
    _ssl_override = os.getenv("DB_SSL_REQUIRE", "").strip().lower()
    if _is_postgres:
        # Supabase Postgres requires SSL. Allow explicit opt-out only via env.
        if _ssl_override in ("0", "false", "no"):
            DATABASES["default"].setdefault("OPTIONS", {}).pop("sslmode", None)
        else:
            DATABASES["default"].setdefault("OPTIONS", {})["sslmode"] = "require"



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Gemini AI
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')


def _env_clean(name: str) -> str:
    """
    Reads env vars and trims accidental wrapping quotes.
    """
    return os.getenv(name, "").strip().strip('"').strip("'")


# Stripe billing (Phase D)
STRIPE_SECRET_KEY = _env_clean("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = _env_clean("STRIPE_WEBHOOK_SECRET")
STRIPE_PRICE_REGULAR_MONTHLY = _env_clean("STRIPE_PRICE_REGULAR_MONTHLY")
STRIPE_PRICE_PREMIUM_MONTHLY = _env_clean("STRIPE_PRICE_PREMIUM_MONTHLY")
STRIPE_PRICE_PREMIUM_YEARLY = _env_clean("STRIPE_PRICE_PREMIUM_YEARLY")
STRIPE_LINK_REGULAR_MONTHLY = _env_clean("STRIPE_LINK_REGULAR_MONTHLY")
STRIPE_LINK_PREMIUM_MONTHLY = _env_clean("STRIPE_LINK_PREMIUM_MONTHLY")
STRIPE_LINK_PREMIUM_YEARLY = _env_clean("STRIPE_LINK_PREMIUM_YEARLY")

# Pantry ingredient catalog (TheMealDB list API; no key required)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "souschef-pantry-cache",
    }
}
PANTRY_USE_INGREDIENT_API = os.getenv("PANTRY_USE_INGREDIENT_API", "True") == "True"
PANTRY_INGREDIENT_LIST_URL = os.getenv(
    "PANTRY_INGREDIENT_LIST_URL",
    "https://www.themealdb.com/api/json/v1/1/list.php?i=list",
)
# 0 (or any non-positive value) means "no cap" in pantry.ingredient_service.
PANTRY_MAX_INGREDIENTS_PER_ZONE = int(os.getenv("PANTRY_MAX_INGREDIENTS_PER_ZONE", "0"))
# Thumbnails: TheMealDB CDN (same project as ingredient list); see ingredient_service.themealdb_ingredient_image_url
PANTRY_SHOW_INGREDIENT_IMAGES = os.getenv("PANTRY_SHOW_INGREDIENT_IMAGES", "True") == "True"

