# Generated by Django 6.0.3 on 2026-04-05 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], default='canceled', max_length=32)),
                ('plan', models.CharField(choices=[('regular', 'Regular'), ('premium', 'Premium')], default='regular', max_length=16)),
                ('billing_interval', models.CharField(blank=True, choices=[('month', 'Month'), ('year', 'Year')], max_length=8, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer subscription',
                'verbose_name_plural': 'customer subscriptions',
            },
        ),
    ]
