# Generated by Django 6.0.3 on 2026-04-05 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_customer_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeUsageMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='Calendar month as "YYYY-MM".', max_length=7)),
                ('count', models.PositiveIntegerField(default=0)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_usage_months', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recipe usage (month)',
                'verbose_name_plural': 'recipe usage (by month)',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('session_key__isnull', True), ('user__isnull', False)), models.Q(('session_key__isnull', False), ('user__isnull', True)), _connector='OR'), name='recipe_usage_month_user_xor_session'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('year_month', 'user'), name='recipe_usage_month_unique_user_month'), models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('year_month', 'session_key'), name='recipe_usage_month_unique_session_month')],
            },
        ),
    ]
