# Generated by Django 6.0.3 on 2026-03-22 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('produce', 'Produce'), ('dairy', 'Dairy'), ('proteins', 'Proteins & Meat'), ('pantry', 'Pantry & Grains'), ('spices', 'Spices & Oils'), ('frozen', 'Frozen'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['user', 'category'], name='pantry_pant_user_id_26d027_idx')],
            },
        ),
    ]
